# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movie
	pod "Gemini"
	pod 'MarqueeLabel'
	pod 'SDWebImage'
	pod 'YouTubePlayer'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'Firebase/Analytics'
	pod 'Alamofire','~>4.7.3'

  

end
